import { REACT_APP_API_BASE_URL } from 'utils/constants/constant';
export const BASE_URL = REACT_APP_API_BASE_URL || ''

export const ENDPOINTS = {
  GET_REGISTERATION_FORM: `${REACT_APP_API_BASE_URL}/user/form`,
  getDropDownValue: `${REACT_APP_API_BASE_URL}/api/report/filter/via/`,
  getUserRoleDropDownValue: `${REACT_APP_API_BASE_URL}/api`,
  generateReport: `/api/report/filter/via/`,
  OLS_HEIGHT_CLEARANCE: `https://dev.coderfuse.com/api/ols_calculate_height`,
  OLS_SUBMITTED_APP: `https://dev.coderfuse.com/api/ols_submitted_app`,
  GET_LOGIN_FORM: `${REACT_APP_API_BASE_URL}/auth/form/login`,
  UPLOAD_IMAGE: `${REACT_APP_API_BASE_URL}/api/file/upload`,
  GET_SITE_ID: `${REACT_APP_API_BASE_URL}/api/siteid`,
  GET_FREQUENCY_BAND: `${REACT_APP_API_BASE_URL}/api/company/allocated-spectrum/get-frequency-spectrum`,
  GET_BTS_EQUIPMENT_DETAIL: `${REACT_APP_API_BASE_URL}/api/bts-equipment`,
  GET_MICROWAVE_EQUIPMENT_DETAIL: `${REACT_APP_API_BASE_URL}/api/mw-equipment`,
  LOGIN: `${BASE_URL}/auth/login`,
  GET_FORM: `${REACT_APP_API_BASE_URL}/api/form`,
  SAVE_FORM: `${REACT_APP_API_BASE_URL}/api/form`,
  CREATE_USER: `${REACT_APP_API_BASE_URL}/api/user/create`,
  CREATE_POC_USER: `${REACT_APP_API_BASE_URL}/api/user/create/poc-user`,
  GET_GROUP: `${REACT_APP_API_BASE_URL}/api/group`,
  GET_PARAMETER:`${REACT_APP_API_BASE_URL}/api/lookup/fcvalues`,
  GET_LOOKUP:`${REACT_APP_API_BASE_URL}/api/lookup`,
  GET_ROLE: `${REACT_APP_API_BASE_URL}/api/role`,
  GET_CERTIFICATE:`${REACT_APP_API_BASE_URL}/api/gmdss-user-certificate`,
  GET_REPORTS: `${REACT_APP_API_BASE_URL}/api/report/filter`,
  GET_SITEID: `${REACT_APP_API_BASE_URL}/api/report/filter/siteid`,
  GET_OPERATOR: `${REACT_APP_API_BASE_URL}/api/report/filter/user/operator`,
  GET_STATUS: `${REACT_APP_API_BASE_URL}/api/report/filter/status`,
  GET_APPTYPE: `${REACT_APP_API_BASE_URL}/api/report/filter/get/app-type`,
  GET_REASON:`${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/reason`,
  GET_USER: `${REACT_APP_API_BASE_URL}/api/user`,
  GET_DYNAMIC_FORM: `${REACT_APP_API_BASE_URL}/api/user/applications/userType`,
  UPDATE_USER: `${REACT_APP_API_BASE_URL}/api/user`,
  GET_COMPANIES: `${REACT_APP_API_BASE_URL}/api/company/get/cmtos-company`,
  GET_WLL_COMPANIES: `${REACT_APP_API_BASE_URL}/api/company/get/wll-company`,
  GET_OTHER_COMPANIES: `${REACT_APP_API_BASE_URL}/api/company/get/other-company`,
  GET_BOARD_MEMBERS: `${REACT_APP_API_BASE_URL}/api/user/get-user/board-members`,
  GET_COMPANY: `${REACT_APP_API_BASE_URL}/api/company`,
  GET_ASSIGNED_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/list/submittedapplications/`,
  GET_GMDSS_ASSIGNED: `${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/`,
  GET_GMDSS_IN_PROGRESS: `${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/inprocess/`,
  GET_GMDSS_APPROVED: `${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/approved/`,
  GET_GMDSS_REJECTED: `${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/rejected/`,
  GET_PROPOSAL_TO_BOARD_MEMBER: `${REACT_APP_API_BASE_URL}/api/gn/wf/proposals/`,
  GET_VIEW_PROPOSAL_TO_BOARD_MEMBER: `${REACT_APP_API_BASE_URL}/api/gn/wf/board/`,
  GET_PARTIAL_APPROVED_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/paapplications/`,
  GET_SECURITY_CLEARANCE_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/gn/wf/sc/proposals/`,
  GET_VIEW_SECURITY_CLEARANCE_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/gn/wf/sc/board/`,
  GET_SAVED: `${REACT_APP_API_BASE_URL}/api/form/app/list`,
  GET_SUBMITED: `${REACT_APP_API_BASE_URL}/api/form/app/list/completedapplications`,
  GET_HISTORY: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/history`,
  GET_APP_HISTORY: `${REACT_APP_API_BASE_URL}/api/gn/wf/certificate/drill/status/`,
  GET_WLL_HISTORY: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/history/wll`,
  GET_FIXED_WIRELESS: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/history/fs`,
  GET_PRN: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/history/prn`,
  GET_BROADCAST: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/history/bc`,
  GET_RETURNED: `${REACT_APP_API_BASE_URL}/api/form/app/list/retunedapplications`,
  GET_RETURNED_OBSERVATION: `${REACT_APP_API_BASE_URL}/api/obs/last`,
  GET_APPLICATION_JSON: `${REACT_APP_API_BASE_URL}/api/form`,
  GENERATE_PROPOSAL: `${REACT_APP_API_BASE_URL}/api/proposal/generate`,
  GENERATE_LEGACY_PROPOSAL: `/api/proposal/generate`,
  GET_GENERATE_PROPOSAL: `${REACT_APP_API_BASE_URL}/api/proposal/generated`,
  GET_BOARD_PERMISSION: `${REACT_APP_API_BASE_URL}/api/wf/query/responsebyapplicant`,
  GET_FORMAL_APPROVAL_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/formal-approval`,
  POST_FORMAL_APPROVAL_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/generate/formal-approval`,
  POST_PROVISIONAL_APPROVAL_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/generate/provisional-approval`,
  POST_REJECTION_APPROVAL_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/generate/rejection`,
  POST_CANCELLATION_APPROVAL_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/generate/cancellation-of-provisional-approval`,
  GET_PROVISIONAL_APPROVAL_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/provisional-approval`,
  GET_CANCELLATION_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/cancellation-of-provisional-approval`,
  GET_REJECTION_LETTER: `${REACT_APP_API_BASE_URL}/api/letter/rejection`,
  GET_OBSERVATION: `${REACT_APP_API_BASE_URL}/api/obs/app`,
  GET_TYPE: `${REACT_APP_API_BASE_URL}/api/proposal/check/app-type`,
  GET_NETWORK_COMPONENT: `${REACT_APP_API_BASE_URL}/api/proposal/get/total-number/network-components`,
  GET_BOARDMEMBER_OBSERVATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/board`,
  GET_WORK_FLOW_FORM: `${REACT_APP_API_BASE_URL}/api/gn/wf/form/action`,
  POST_ASSIGN_FORWARD: `${REACT_APP_API_BASE_URL}/api/gn/wf/assign`,
  SECURITY_FORWARD: `${REACT_APP_API_BASE_URL}/api/gn/wf/bm/external`,
  GMDSS_SEND_TO_OPERATOR: `${REACT_APP_API_BASE_URL}/api/gmdss-user-certificate/update/certificate/recordviahistory`,
  POST_FORWARD: `${REACT_APP_API_BASE_URL}/api/gn/wf/action`,
  SEND_TO_USER:`${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/reject`,
  CLOSE_COMPLAINT: `${REACT_APP_API_BASE_URL}/api/gn/wf/complaint/close`,
  PEMRA_COMPLAINT: `${REACT_APP_API_BASE_URL}/api/gn/wf/sendtopemra`,
  PTA_COMPLAINT: `${REACT_APP_API_BASE_URL}/api/gn/wf/sendtopta`,
  FAB_COMPLAINT: `${REACT_APP_API_BASE_URL}/api/gn/wf/sendtofab`,
  UPDATE_STATUS: `${REACT_APP_API_BASE_URL}/api/gn/wf/update/app/status`,
  FMS_COMPLAINT: `${REACT_APP_API_BASE_URL}/api/gn/wf/sendtofms`,
  ZO_COMPLAINT: `${REACT_APP_API_BASE_URL}/api/gn/wf/sendtozonal`,
  APPROVED_GMDSS_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/approve`,
  APPROVED_GMDSS_ED_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/gm/approve`,
  REJECTED_GMDSS_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/gmdss/reject`,
  REJECTED_GMDSS_ED_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/gm/reject`,
  APPROVE_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/approve`,
  REGRETTED_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/reject`,
  PARTIAL_APPROVE_APPLICATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/partialapprove`,
  OBSERVATION: `${REACT_APP_API_BASE_URL}/api/gn/wf/obs`,
  GET_NOTIFICATION: `${REACT_APP_API_BASE_URL}/api/notification/fetch`,
  MARK_NOTIFICATION: `${REACT_APP_API_BASE_URL}/api/notification/mark`,
  SEND_TO_OPERATOR: `${REACT_APP_API_BASE_URL}/api/gn/wf/operator`,
  COMPANY: `${REACT_APP_API_BASE_URL}/api/company`,
  LICENSE_INFO: `${REACT_APP_API_BASE_URL}/api/company/license`,
  ALLOCATED_SPECTRUM: `${REACT_APP_API_BASE_URL}/api/company/allocated-spectrum`,
  GET_REGION: `${REACT_APP_API_BASE_URL}/api/company/license/region`,
  COMPANY_ATTACHMENT: `${REACT_APP_API_BASE_URL}/api/company/attachments`,
  APPROVED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/approved`,
  EMPLOYEE_APPROVED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/form/app/list/approvedapplications`,
  PARTIAL_APPROVED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/provisional`,
  EMPLOYEE_PARTIAL_APPROVED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/form/app/list/partialapprovedapplications`,
  REJECTED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/rejected`,
  EMPLOYEE_REJECTED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/form/app/list/rejectedapplications`,
  CANCELLED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/cancelled`,
  EMPLOYEE_CANCELLED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/form/app/list/cancelledapplications`,
  COMPLETED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/gn/wf/app/underprocess`,
  EMPLOYEE_COMPLETED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/form/app/list/completedapplications`,
  RETUNED_APPLICATIONS: `${REACT_APP_API_BASE_URL}/api/form/app/list/retunedapplications`,
  GET_ALERT_TIMELINE: `${REACT_APP_API_BASE_URL}/api/alert`,
  GET_UPDATE_ALERT_TIMELINE: `${REACT_APP_API_BASE_URL}/api/setup/alert`,
  UPDATE_ALERT_TIMELINE: `${REACT_APP_API_BASE_URL}/api/setup/alert`,
  GetUserGroup: `${REACT_APP_API_BASE_URL}/api/ug/all`,
  GET_USER_BY_GROUP_ID: `${REACT_APP_API_BASE_URL}/api/ug/users`,
  GET_ROLE_BY_ROLE_ID: `${REACT_APP_API_BASE_URL}/api/ro/options`,
  GET_GROUP_BY_ROLE_ID: `${REACT_APP_API_BASE_URL}/api/gr/roles`,
  SUBMIT_USER_BY_GROUP_ID: `/api/ug`,
  SUBMIT_ROLE_BY_PERMISSON_ID: `/api/ro`,
  SUBMIT_ROLE_BY_GROUP_ID: `/api/gr`,
  GET_CERTIFICATE_STATUS: `${REACT_APP_API_BASE_URL}/api/gn/wf/certificate/status`,
  GET_USER_ROLES: `${REACT_APP_API_BASE_URL}/api/mo`,
  APPLICATION_FORM: `${REACT_APP_API_BASE_URL}/api/form`,
  GET_USER_PERMISSIONS: `${REACT_APP_API_BASE_URL}/api/gn/permissions/`,
  GET_PROVINCE : `${REACT_APP_API_BASE_URL}/api/gn/province`,
  GET_DISTRICT : `${REACT_APP_API_BASE_URL}/api/gn/district/`,
  GET_CITY : `${REACT_APP_API_BASE_URL}/api/gn/city/`,
  GET_ONLY_CITY : `${REACT_APP_API_BASE_URL}/api/gn/city`,
  GET_BASE_STATION: `${REACT_APP_API_BASE_URL}/api/network-component`,
  GET_MOBILE_CONNECTED: `${REACT_APP_API_BASE_URL}/api/mobile-connected`,
  GET_HANDHELD_CONNECTED: `${REACT_APP_API_BASE_URL}/api/handheld-connected`,
  GET_BM_QUERY: `${REACT_APP_API_BASE_URL}/api/wf/query`,
  GET_STAFF_BM_QUERY: `${REACT_APP_API_BASE_URL}/api/wf/query/staffview`,
  GET_STAFF_BOARD_QUERY: `${REACT_APP_API_BASE_URL}/api/wf/query/bmView`,
  POST_BM_QUERY: `${REACT_APP_API_BASE_URL}/api/wf/query/operator`,
  POST_STAFF_BM_QUERY: `${REACT_APP_API_BASE_URL}/api/wf/query/bm`,
  COMPLAINTS: `${REACT_APP_API_BASE_URL}/api/complaint`,
  ASSIGNED_COMPLAINTS: `${REACT_APP_API_BASE_URL}/api/gn/wf/complaint/`,
  INPROGRESS_WFlOW_COMPLAINTS: `${REACT_APP_API_BASE_URL}/api/gn/wf/complaint/inprocess/`,
  CLOSED_WFlOW_COMPLAINTS: `${REACT_APP_API_BASE_URL}/api/gn/wf/complaint/closed/`,
  CMTO_WLL_COMPLAINTS: `/api/complaint/CMTO-WLL`,
  GET_COMPLAINTS_OPERATORS: `${REACT_APP_API_BASE_URL}/api/complaint/operators`,
  NON_CMTO_WLL_COMPLAINTS: `/api/complaint/NON-CMTO-WLL`,  
  VERIFY_ACCOUNT: `${REACT_APP_API_BASE_URL}/api/user/user/account/verify`,  
  CREATE_GMDSS_USER:`/api/gmdss-user-certificate/create`,
  GET_GMDSS_USER_HISTORY:`api/gn/wf/gmdss/cetificates/`,
  REJECT_GMDSS_OPERATOR:`/api/gn/wf/gmdss/reject/`,
  GET_BASE64:`/api/gmdss-user-certificate/media/`,
  GET_STATION_REPORT_DROPDOWNS:`/api/station/report/dropdowns`,
  GET_STATION_REPORT_DATA:`/api/station/reports`,
  POST_STATION_REPORT:`/api/station/report/create`,
  GET_ALL_STATION_REPORTS:`/api/station/reports`,
  ADD_NEW_STATION_REPORTS:`/api/complaint/department/assign`,
  DELETE_FILE: `/api/file/uploads/drop`,
  GET_MW_EQUIPMENT_DETAILS: `${REACT_APP_API_BASE_URL}/api/mw-equipment/all-mw-equipment-user`,
  DELETE_MW_EQUIPMENT_DETAILS: `${REACT_APP_API_BASE_URL}/api/mw-equipment`,
  GET_BTS_EQUIPMENT_DETAILS: `${REACT_APP_API_BASE_URL}/api/bts-equipment/all-bts-equipment-user`,  
  DELETE_BTS_EQUIPMENT_DETAILS: `${REACT_APP_API_BASE_URL}/api/bts-equipment`,  
  GENERATE_GMDSS_REOPORT:`/api/gmdss-user-certificate/gmdss/generate/report`,
  UPDATE_STATION_REPORT:`/api/station/report/update`,
  GET_COMPLAINT_HISTORY:`/api/complaint/reports/station`,
  GET_LETTER_FLAG: `/api/gn/wf/certificate/drill/status`,
  GET_ATTACHMENTS: `api/file/getAttachments`
}
export const REQUEST_TYPES = {
  DELETE: 'DELETE',
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
}
